Controllers films users
MityaDD/java-filmorate pull request #4
Opened 2023-02-28 05:11 UTC by MityaDD

2023-02-28 05:23 UTC, MityaDD commented
Начал проект с добавлением основных классов и методов

2023-02-28 20:21 UTC, Fleaman777 requested changes

2023-02-28 20:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean isValid(Film film) {
хорошо, что вынес валидацию в отдельный метод, так ее будет проще поддерживать

2023-02-28 20:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() == 0 || film.getDescription().length() > 200) {
значение 200 можно было бы вынести в константу, 
таким образом, будет единое место установки этого значения, а так же благодаря названию, будет понимание, что именно это за велечина

2023-02-28 20:21 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            updatedUser.setBirthday(user.getBirthday());
на данном этапе разработки это действие может показаться лишнем, т.к. в мапу сохраняется тот же объект, что передается в контроллер, 

но в целом идея нормальная, т.к. в будущем это будут разные объекты

2023-02-28 20:21 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    }
отличный метод setUp делает всю необходимую инициализацию перед тестами

2023-02-28 22:04 UTC, MityaDD commented
Убрал magic number

2023-03-01 06:25 UTC, Fleaman777 approved these changes

2023-03-01 07:12 UTC, merged