initial commit #10.1
MityaDD/java-filmorate pull request #5
Opened 2023-03-13 02:55 UTC by MityaDD

2023-03-13 20:05 UTC, Fleaman777 requested changes

2023-03-13 20:05 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Map<Integer, Film> allFilms();
как мне кажется, allFilms скорее будет возвращать List<Film>, чем Map
Мап тоже может возвращаться, но это лучше как-нибудь оторбазить в названии метода, что бы не было некоторого недопонимания

2023-03-22 04:29 UTC, MityaDD commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
выполнил.

2023-03-22 04:29 UTC, MityaDD commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    }
сделал

2023-03-22 04:32 UTC, MityaDD commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    }
как я понял, сенсей любит стримы)

2023-03-22 04:39 UTC, MityaDD commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Map<Integer, Film> allFilms();
Оставил мапу, имя метода исправил. Кмк мапа - это более гибко и надежно. В смысле для начинающих. Тем более я не знаю, какую еще логику будем реализовывать в следующих спринтах, а у меня был опыт с kanban, когда я сделал изначально List, а на последних спринтах появилась проблема достать таску по id и при этом не триггернуть историю. Пришлось переписывать много строчек, начиная с интерфейса и поменять List на Map

2023-03-22 04:40 UTC, MityaDD commented
Внес все рекомендуемые исправления.

2023-03-22 18:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Map<Integer, Film> allFilms();
хорошо, понял тебя 

ну да, согласен, если есть возможность сделать мапу, и она логически нормально встраивается и не нужно передеделывать кучу логики, что бы ее заполнить, то можно ей и воспользоваться 

но листы достаточно часто встречаются при работе с бд в spring-jpa/hibernate , 
думаю поэтому, у меня и родился этот комментарий)

2023-03-22 18:59 UTC, Fleaman777 approved these changes

2023-03-26 17:06 UTC, merged