Add database
MityaDD/java-filmorate pull request #7
Opened 2023-04-08 10:07 UTC by MityaDD

2023-04-09 09:32 UTC, Fleaman777 requested changes

2023-04-09 09:32 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    String name;
поля должны быть private

2023-04-09 09:32 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    }
попробуй сделать этот метод через стрим, должно получится покомпактней и посовременней )

2023-04-09 09:32 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/DbGenreStorage.java
> +    public HashSet<Genre> getFilmGenres(Integer filmId) {
возврощаемый тип лучше указать более широкий Set, 
так полиморфизм будет работать лучше

2023-04-09 09:32 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> + */
закомментированный код можно удалить, 
в 90% он потом не используется, 
а если он даже и понадобится, то его можно будет восстановить через гит лог

2023-04-09 11:15 UTC, MityaDD commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    String name;
вроде 5 раз просмотрел перед отправкой, а все равно проглядел) Исправил.

2023-04-09 11:21 UTC, MityaDD commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    }
Я так давно не писал обычный цикл, что было аж жалко удалять вот эту вот ламповую i++. Однако искусство требует эстетических жертв. Стримы так стримы))

2023-04-09 11:22 UTC, MityaDD commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/DbGenreStorage.java
> +    public HashSet<Genre> getFilmGenres(Integer filmId) {
Выполнил.

2023-04-09 11:23 UTC, MityaDD commented
Сделал все рекомендуемые исправления.

2023-04-10 06:11 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java
> +    }
хех, 
ну да, про i++ согласен, 
что-то на олдскульном))

2023-04-10 06:12 UTC, Fleaman777 approved these changes

2023-04-10 06:48 UTC, merged